name: Create Installer Image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-installer-image:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true

      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check cached image
        id: cache-raspios
        uses: actions/cache/restore@v3
        with:
          path: ~/raspios.img
          key: raspios.img

      - name: Download image
        if: ${{ steps.cache-raspios.outputs.cache-hit != 'true' }}
        run: |
          wget https://downloads.raspberrypi.com/raspios_armhf/images/raspios_armhf-2023-10-10/2023-10-10-raspios-bookworm-armhf.img.xz -O ~/raspios.img.xz
          unxz ~/raspios.img.xz
          true || rm -rf ~/raspios.img.xz

      - name: Cache image
        uses: actions/cache/save@v3
        with:
          path: ~/raspios.img
          key: raspios.img

      - name: Checkout assests
        uses: actions/checkout@v4
        with:
          path: image-build

      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          path: kernel
          repository: Open-Surface-RT/grate-linux
          ref: microsoft-surface-rt

      - name: Load ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: kernel-ccache

      - name: Build kernel
        run: |
          sudo apt update
          sudo apt install build-essential gcc-arm-linux-gnueabihf ccache libncurses-dev flex bison libssl-dev bc libelf-dev libudev-dev -y
          mkdir -p ~/.ccache
          ccache -z
          cd ${GITHUB_WORKSPACE}/kernel
          ARCH=arm make ARCH=arm CC="ccache arm-linux-gnueabihf-gcc" CXX="ccache arm-linux-gnueabihf-g++" tegra_defconfig
          cat ${GITHUB_WORKSPACE}/image-build/.github/workflows/tegra_surface_rt_defconfig >> .config
          ARCH=arm yes '' | make ARCH=arm CC="ccache arm-linux-gnueabihf-gcc" CXX="ccache arm-linux-gnueabihf-g++" CROSS_COMPILE=arm-linux-gnueabihf- -j $(nproc)

      - name: ccache statistics
        run: |
          ccache -s

      - name: Save ccache
        uses: actions/cache/save@v3
        id: cache
        with:
          path: ~/.ccache
          key: kernel-ccache

      - name: Patch image
        run: |
          # expand rootfs for kernel modules
          sudo apt update
          sudo apt install parted -y
          dd if=/dev/zero bs=1MiB of=~/raspios.img conv=notrunc oflag=append count=500

          # mount
          LOOPDEV="$(sudo losetup -P --show -f ~/raspios.img)"
          sudo parted "${LOOPDEV}" resizepart 2 100%
          sudo resize2fs -f "${LOOPDEV}p2"

          sudo mkdir -p /mnt/boot /mnt/rootfs
          sudo mount "${LOOPDEV}p1" /mnt/boot
          sudo mount "${LOOPDEV}p2" /mnt/rootfs

          # copy files
          sudo cp -rf ${GITHUB_WORKSPACE}/image-build/.github/workflows/efi /mnt/boot/
          sudo cp ${GITHUB_WORKSPACE}/image-build/.github/workflows/startup.nsh /mnt/boot/
          sudo cp ${GITHUB_WORKSPACE}/image-build/.github/workflows/startup.emmc.nsh /mnt/boot/
          sudo cp ${GITHUB_WORKSPACE}/image-build/.github/workflows/How-to-Install-on-Internal-Storage.txt /mnt/rootfs/
          cd ${GITHUB_WORKSPACE}/kernel
          sudo cp arch/arm/boot/zImage /mnt/boot/
          sudo cp arch/arm/boot/dts/tegra30-microsoft-surface-rt-efi.dtb /mnt/boot/
          sudo ARCH=arm make INSTALL_MOD_PATH=/mnt/rootfs modules_install

          sudo umount /mnt/boot /mnt/rootfs
          sudo resize2fs -fM "${LOOPDEV}p2"
          sudo losetup --detach "${LOOPDEV}"

      - name: Split image
        run: |
          gzip -f ~/raspios.img
          split -b 2000m ~/raspios.img.gz ~/raspios.img.gz.

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ~/raspios.img.gz.*